### ISSUE TITLE
ChineseCalendar.java problem

### ISSUE THREAD

**Issue by saisot2006** [Carbs0126/GregorianLunarCalendar#12]
Hi, I got error in ChineseCalendar.java
at these lines:
public ChineseCalendar(boolean isChinese, int y, int m, int d) {
        if (isChinese) {
            set(CHINESE_YEAR, y);
            set(CHINESE_MONTH, m);
            set(CHINESE_DATE, d);
        } else {
            set(y, m, d);
        }

My Android Studio kept saying CHINESE_YEAR, CHINESE_MONTH, CHINESE_DATE must be one of Calendar.ERA, DAY_OF_MONTH...
Thx.

**Comment by Carbs0126** [comment]
just resolved this problem , check out the latest code please.
