### ISSUE TITLE
是否可以帮我解决一下问题

### ISSUE THREAD

**Issue by 957919019** [Carbs0126/GregorianLunarCalendar#4]
我将用此控件放在了popWindow上，在Activity上点击按钮，弹出该控件，选择时间是没有问题的，但是如果不滑动，时间就是null，有没有办法解决？

**Comment by Carbs0126** [comment]
这个工程中有个dialog示例，你把那个示例中的主要代码赋值过去试下。
另外，你说的不滑动时间就是null具体是什么意思？使用了什么方法获取时间呢？
你在popupwindow的showasdrop( ) 后，接着调用 
```
mGLCView.init();//init has no scroll effection, to today
```
应该没问题

如果不行的话，麻烦把代码片段贴上来我看下吧

**Comment by 957919019** [comment]
找到原因了，是因为我在给点击事件的时候直接把mGLCView的setOnDateChangedListener传到上一级页面了，看了你的源码以后才发现，按钮点击事件的时候也要用Calendar calendar = calendarData.getCalendar();再获取一次，我用自己的Demo反复和你的源码对比了几次才发现，dialog我不太喜欢用，所以自己封装了PopupWindow，谢谢了

**Comment by Carbs0126** [comment]
不客气，感谢对此程序的关注
